server:
  port: 9527
  servlet:
    # 应用的访问路径
    context-path: /
  max-http-header-size: 10240000
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-http-header-size: 10240000


spring:
  mvc:
    hiddenmethod:   #过滤器
      filter:
        enabled: true     # 默认为false,在使用@deletemapping时post请求报405错误，改为true
                    # 不管用，将@DeleteMapping换成@RequestMapping(method=post)

  servlet:
    multipart:
      max-file-size: 5GB    #最大支持文件大小
      max-request-size: 10GB    #最大支持请求大小
      enabled: true     #是否支持 multipart 上传文件
      file-size-threshold: 0    #支持文件写入磁盘
      resolve-lazily: false  #是否支持 multipart 上传文件时懒加载

  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        primary:
          username: root
          password: a709046532
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai


  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: cc.mrbird.febs.system.domain,cc.mrbird.febs.job.domain,cc.mrbird.febs.project.domain,cc.mrbird.febs.filemanager.model
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


febs:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/favicon.ico
    # token有效期，单位秒
    jwtTimeOut: 3600
  # Swagger相关配置
  swagger:
    basePackage: cc.mrbird.febs
    title: FEBS VUE API
    description: FEBS VUE API Document.
    version: 2.0
    author: MrBird
    url: https://mrbird.cc
    email: 852252810@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html

# 最大导出数量
export:
  maxCount: 10000


# 上传文件存储路径
prop:
  upload-folder: D:/files
